In [4]:
# GENERAL LIBRAIRIES IMPORT
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [5]:
# DATA IMPORT
netflix = pd.read_csv('/Users/helmichaaba/Downloads/netflix.csv')
netflix.drop('Unnamed: 0', axis = 1, inplace=True)
netflix.head()

before_90s  90s  2000s  movie  other  tv movie  video movie  Action  \
0         0.0  1.0    0.0      0      0         0            1       0   
1         0.0  1.0    0.0      1      0         0            0       1   
2         0.0  0.0    1.0      1      0         0            0       0   
3         0.0  1.0    0.0      1      0         0            0       0   
4         1.0  0.0    0.0      0      0         0            1       0   

   Documentary  Comedy  ...  Thriller  Romance  Other_genre  United States  \
0            0       0  ...         0        0            1              1   
1            0       0  ...         0        0            1              0   
2            1       1  ...         0        0            1              1   
3            0       1  ...         0        0            1              1   
4            1       0  ...         0        0            1              1   

   United Kingdom  France  Other_country  English  Other_language  category  
0               0       0              0        1               0     niche  
1               0       0              1        0               1     other  
2               0       0              0        1               1     other  
3               0       0              0        1               0     other  
4               0       0              0        1               0     niche  

[5 rows x 21 columns]

In [6]:
# SKLEARN IMPORTS
from sklearn.tree import DecisionTreeClassifier , plot_tree
from sklearn.metrics import accuracy_score, recall_score, precision_score, roc_auc_score, roc_curve, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
import warnings 
warnings.filterwarnings('ignore')

In [7]:
# SYNTHESIS FUNCTION
def synthetise(model, X_train, X_test, y_train, y_test):
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    y_train_score = model.predict_proba(X_train)
    y_test_score = model.predict_proba(X_test)
    model_name = type(model).__name__
    print(re.sub(r"(\w)([A-Z])", r"\1 \2", model_name).upper())
    print('====================')
    print('TRAIN dataset')
    print(f'Accuracy score: {accuracy_score(y_train, y_train_pred):.1%}')
    print(f'Recall score: {recall_score(y_train, y_train_pred, average="weighted"):.1%}')
    print(f'Precision score: {precision_score(y_train, y_train_pred, average="weighted"):.1%}')
    print(f'ROC_AUC score: {roc_auc_score(y_train, y_train_score, average="weighted", multi_class="ovo"):.1%}')
    print(f'Confusion matrix')
    print(confusion_matrix(y_train, y_train_pred))
    print('====================')
    print('TEST dataset')
    print(f'Accuracy score: {accuracy_score(y_test, y_test_pred):.1%}')
    print(f'Recall score: {recall_score(y_test, y_test_pred, average="weighted"):.1%}')
    print(f'Precision score: {precision_score(y_test, y_test_pred, average="weighted"):.1%}')
    print(f'ROC_AUC score: {roc_auc_score(y_test, y_test_score, average="weighted", multi_class="ovo"):.1%}')
    print(f'Confusion matrix')
    print(confusion_matrix(y_test, y_test_pred))

In [8]:
# DATA PREPARATION

X = netflix.drop('category', axis = 1)
y = netflix.category

# random_state = 42 for reproductibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
GaussianNB?

Init signature: GaussianNB(*, priors=None, var_smoothing=1e-09)
Docstring:     
Gaussian Naive Bayes (GaussianNB)

Can perform online updates to model parameters via :meth:`partial_fit`.
For details on algorithm used to update feature means and variance online,
see Stanford CS tech report STAN-CS-79-773 by Chan, Golub, and LeVeque:

    http://i.stanford.edu/pub/cstr/reports/cs/tr/79/773/CS-TR-79-773.pdf

Read more in the :ref:`User Guide <gaussian_naive_bayes>`.

Parameters
----------
priors : array-like of shape (n_classes,)
    Prior probabilities of the classes. If specified the priors are not
    adjusted according to the data.

var_smoothing : float, default=1e-9
    Portion of the largest variance of all features that is added to
    variances for calculation stability.

    .. versionadded:: 0.20

Attributes
----------
class_count_ : ndarray of shape (n_classes,)
    number of training samples observed in each class.

class_prior_ : ndarray of shape (n_classes,)
    probability

In [11]:
# DECISION TREE CLASSIFIER
## Naive view: default hyperparameters & all features
### Model fitting
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [12]:
### Synthesis
synthetise(gnb, X_train, X_test, y_train, y_test)

GAUSSIAN NB
TRAIN dataset
Accuracy score: 33.6%
Recall score: 33.6%
Precision score: 74.1%
ROC_AUC score: 72.2%
Confusion matrix
[[ 676   14    5]
 [ 271  761   37]
 [2654  631  393]]
TEST dataset
Accuracy score: 30.0%
Recall score: 30.0%
Precision score: 76.5%
ROC_AUC score: 71.4%
Confusion matrix
[[149   4   2]
 [ 64 159   6]
 [713 164 100]]


In [10]:
### Conclusions
#### The model doesn't work well, results are overfitted, we reject the model.